import Head from 'next/head'
import Image from 'next/image'
import Avatar from '../components/Avatar'
import {MicrophoneIcon, SearchIcon, ViewGridIcon} from "@heroicons/react/outline"
import Footer from '../components/Footer'
import { useRef } from 'react'
import router, { useRouter } from 'next/router'

export default function Home() {

  const searchInputRef = useRef(null); 

  const search = (e) => { 
    e.preventDefault();
    const term = searchInputRef.current.value;

    if(!term) return;

    router.push(`/search?term=${term}`);

  };



  return (
    <div className="bg-blue-300 bg-gradient-to-r from-blue-300 to-green-300
    flex flex-col items-center justify-center h-screen">
      <Head>
        <title>Firezilla</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="flex w-full p-5 justify-between
      text-sm text-gray-700">
          <div className="flex space-x-4 items-center">
            <p className="link">About</p>
            <p className="link">Store</p>
          </div>
          <div className="flex space-x-4 items-center">
            <p className="link">Firemail</p>
            <p className="link">Images</p>

            <ViewGridIcon className="h-10 w-10 p-2
            rounded-full hover:bg-gray-100 cursor-pointer"/>

            <Avatar url='https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLaoiVChJYmLSdfsWtgKL_deeSguvjFYeHqw&usqp=CAU'/>
          </div>
      </header>

      <form className="flex flex-col items-center flex-grow w-4/5">
        <Image 
           src="https://raw.githubusercontent.com/Raven1233/Projectwork/main/logo.svg"
           width={500}
           height={300}
           alt="image"
        />
        <div className="flex w-full hover:shadow-lg 
        focus-within:shadow-lg max-w-md rounded-full
        border border-blue-400 px-5 py-3 items-center
        sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500"/>
          <input type="text" ref={searchInputRef} className="flex-grow focus:outline-none bg-transparent"/>
          <MicrophoneIcon className="h-5"/>
        </div>
 
        <div className="flex flex-col w-1/2 space-y-2 justify-center mt-8
        sm:space-y-0 sm:flex-row sm:space-x-4">
          <button onClick={search} className="btn">Search Web</button>
          <button onClick={search} className="btn">I&#39;m Fired Up</button>
        </div>

      </form>

      <Footer />

    </div>
  )
}
